.code

Questions   BYTE "Taj Mahal|||||||||||||||", 0
Questions2  BYTE "Eiffel Tower||||||||||||", 0
Questions3  BYTE "Great Wall of China|||||", 0
Questions4  BYTE "Pyramids of Giza||||||||", 0
Questions5  BYTE "Statue of Liberty|||||||", 0
Questions6  BYTE "Binary Search|||||||||||", 0
Questions7  BYTE "Cloud Computing|||||||||", 0
Questions8  BYTE "Artificial Intelligence|", 0
Questions9  BYTE "Blockchain||||||||||||||", 0
Questions10 BYTE "HTTP||||||||||||||||||||", 0

Hint_Questions     BYTE "Famous white marble mausoleum in India.                    ", 0
Hint_Questions_1_2 BYTE "Built by Shah Jahan for his wife Mumtaz.                   ", 0
Hint_Questions_1_3 BYTE "One of the Seven Wonders of the World.                     ", 0
Hint_Questions_1_4 BYTE "A blend of Indian, Persian, and Mughal styles.             ", 0
Hint_Questions_1_5 BYTE "Its name means (Crown of the Palace) in Persian.           ", 0
Hint_Questions_1_6 BYTE "It is located in the city of Agra, Uttar Pradesh.          ", 0

Hint_Questions_2_1 BYTE "A famous iron tower in Paris, France.                      ", 0
Hint_Questions_2_2 BYTE "It was designed by Gustave Eiffel.                         ", 0
Hint_Questions_2_3 BYTE "It was completed in 1889 for the World Expo.               ", 0
Hint_Questions_2_4 BYTE "It is one of the most visited paid monuments.              ", 0
Hint_Questions_2_5 BYTE "It stands 324 meters tall and is iconic.                   ", 0
Hint_Questions_2_6 BYTE "This is a wrought-iron lattice tower.                      ", 0

Hint_Questions_3_1 BYTE "A massive wall that stretches across China.                ", 0
Hint_Questions_3_2 BYTE "It was built to protect China from invasions.              ", 0
Hint_Questions_3_3 BYTE "Construction began as early as the 7th century BC.         ", 0
Hint_Questions_3_4 BYTE "It stretches over 13,000 miles in total.                   ", 0
Hint_Questions_3_5 BYTE "It’s visible from space with the naked eye.                ", 0
Hint_Questions_3_6 BYTE "The total length of this structure is over 13,000 miles.   ", 0

Hint_Questions_4_1 BYTE "Ancient stone structures in Egypt.                         ", 0
Hint_Questions_4_2 BYTE "The Great Pyramid is one of the Seven Wonders.             ", 0
Hint_Questions_4_3 BYTE "They were tombs for Pharaohs in ancient times.             ", 0
Hint_Questions_4_4 BYTE "Located on the outskirts of Cairo.                         ", 0
Hint_Questions_4_5 BYTE "The Pyramids are over 4,500 years old.                     ", 0
Hint_Questions_4_6 BYTE "This structure has stood for over 4,500 years.             ", 0

Hint_Questions_5_1 BYTE "A giant statue located in New York Harbor.                 ", 0
Hint_Questions_5_2 BYTE "It symbolizes freedom and democracy.                       ", 0
Hint_Questions_5_3 BYTE "Gifted to the U.S. by France in 1886.                      ", 0
Hint_Questions_5_4 BYTE "It stands 151 feet tall and holds a torch.                 ", 0
Hint_Questions_5_5 BYTE "It was designed by sculptor Frédéric Auguste Bartholdi.    ", 0
Hint_Questions_5_6 BYTE "It is one of the most recognizable symbols of the US.      ", 0

Hint_Questions_6_1 BYTE "An algorithm for finding an item in a sorted list.         ", 0
Hint_Questions_6_2 BYTE "Works by repeatedly dividing the search interval in half.  ", 0
Hint_Questions_6_3 BYTE "Has a time complexity of O(log n).                         ", 0
Hint_Questions_6_4 BYTE "It starts with the middle element and narrows down.        ", 0
Hint_Questions_6_5 BYTE "It’s more efficient than linear search for large lists.    ", 0
Hint_Questions_6_6 BYTE "It is commonly used in CS for searching sorted data.       ", 0

Hint_Questions_7_1 BYTE "Using remote servers to store and process data.            ", 0
Hint_Questions_7_2 BYTE "It enables on-demand access to computing resources.        ", 0
Hint_Questions_7_3 BYTE "Popular services include AWS, Google Cloud, and Azure.     ", 0
Hint_Questions_7_4 BYTE "Reduces need for physical hardware and infrastructure.     ", 0
Hint_Questions_7_5 BYTE "It offers scalability, flexibility, and cost efficiency.   ", 0
Hint_Questions_7_6 BYTE "It allows accessing data and services over the internet.   ", 0

Hint_Questions_8_1 BYTE "Field of computer science that mimics human intelligence.  ", 0
Hint_Questions_8_2 BYTE "Includes machine learning, NLP and more.                   ", 0
Hint_Questions_8_3 BYTE "Can perform tasks like problem-solving.                    ", 0
Hint_Questions_8_4 BYTE "It powers virtual assistants like Siri and Alexa.          ", 0
Hint_Questions_8_5 BYTE "It is used in robotics, automation, and data analysis.     ", 0
Hint_Questions_8_6 BYTE "Popular technologies within this field include ML, DL.     ", 0

Hint_Questions_9_1 BYTE "A decentralized ledger of transactions.                    ", 0
Hint_Questions_9_2 BYTE "It is the technology behind cryptocurrencies.              ", 0
Hint_Questions_9_3 BYTE "Each block contains a record of several transactions.      ", 0
Hint_Questions_9_4 BYTE "It is secure because it is immutable and transparent.      ", 0
Hint_Questions_9_5 BYTE "Widely used in finance, supply chains, and more.           ", 0
Hint_Questions_9_6 BYTE "Widely used in applications beyond cryptocurrencies.       ", 0

Hint_Questions_10_1 BYTE "A protocol used for transferring web pages.                ", 0
Hint_Questions_10_2 BYTE "It defines how messages are formatted and transmitted.     ", 0
Hint_Questions_10_3 BYTE "It is the foundation of data communication on the web.     ", 0
Hint_Questions_10_4 BYTE "It is request-response system between client and server.   ", 0
Hint_Questions_10_5 BYTE "It is commonly used for online banking.                    ", 0
Hint_Questions_10_6 BYTE "It uses SSL/TLS to secure communications.                  ", 0
